cen = int(input("Input centimeters length "))
kilos = int(input("Input kilos weight "))
inch = float(cen / 2.54)
pounds = float(kilos * 2.205)
print (kilos, "kilograms and ", cen, " centimeters equals ", pounds, " pounds and ", inch, " inches" )